# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:            Your awesome title
email:            your-email@example.com
description:      >- # this means to ignore newlines until "baseurl:"
                  Write an awesome description for your new site here. You can edit this
                  line in _config.yml. It will appear in your document head meta (for
                  Google search results) and in your feed.xml site description.
baseurl:          "" # the subpath of your site, e.g. /blog
url:              "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme:            minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

classify:
  layout:  subjects
  enabled: all
  permalinks:
    year:            "/:year/"
    month:           "/:year/:month/"
    day:             "/:year/:month/:day/"
    year_week:       "/:year/week/:week/"
    week:            "/week/:week/"
    tag:             "/tag/:tag/"
    category:        "/category/:category/"
    categories:      "/categories/:categories/"
    tags:            "/tags/:tags/"
    category_tag:    "/category_tag/:category/:tag/"
    category_tags:   "/category_tags/:category/:tags/"
    categories_tags: "/categories_tags/:categories/:tags/"

templates: &default
  category: 0

cjyb: &cjyb
  tags: [ 1, 2, 3, 6 ]
  count: 4

yule: &yule
  tags: [ 1, 2, 3, 6 ]
  count: 4

lkui: &lkui
  tags: [ 1, 2, 3, 6 ]
  count: 4

icui: &icui
  tags: [ 1, 2, 3, 6 ]
  count: 4

jnts: &jnts
  tags: [ 1, 6 ]
  count: 4

hrkr: &hrkr
  tags: [ 1, 2, 3 ]
  count: 4

ugho: &ugho
  tags: [ 1, 2, 3, 6 ]
  count: 4

tsxb: &tsxb
  tags: [ 1, 2, 6 ]
  count: 5

yewu: &yewu
  tags: [ 1, 2, 3, 5 ]
  count: 4

viiu: &viiu
  tags: [ 1, 2, 3, 5 ]
  count: 4

rfqk: &rfqk
  tags: [ 1, 2, 3, 6 ]
  count: 4

yiln: &yiln
  tags: [ 1, 2, 3, 5 ]
  count: 4

tally:
  default: *default
  templates:
    cjyb: *cjyb
    yule: *yule
    lkui: *lkui
    icui: *icui
    jnts: *jnts
    hrkr: *hrkr
    ugho: *ugho
    tsxb: *tsxb
    yewu: *yewu
    viiu: *viiu
    rfqk: *rfqk
    yiln: *yiln

